version: '3.12'

services:

  db:
    image: postgres:14.2-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: stats_test
      POSTGRES_USER: stats_test
      POSTGRES_PASSWORD: stats_test
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      STATS_CORE_SETTING_DATABASES: '{"default":{"HOST":"db"}}'
      STATS_CORE_SETTING_LOCAL_SETTINGS_PATH: 'local/settings.prod.py'

volumes:
  postgresql-data:
    driver: local
